here::i_am("run.R")
library(here)
library(fs)
library(targets)
# tar_config_set(script = "_targets_ceda_to_lev1.R", store = "_targets_ceda_to_lev1", project = "ceda_to_lev1")
# tar_config_set(script = "_targets_hist_to_lev1.R", store = "_targets_hist_to_lev1", project = "hist_to_lev1")
# tar_config_set(script = "_targets_curr_to_lev1.R", store = "_targets_curr_to_lev1", project = "curr_to_lev1")

Sys.setenv(TAR_PROJECT = "ceda_to_lev1")
Sys.setenv(TAR_PROJECT = "hist_to_lev1")
Sys.setenv(TAR_PROJECT = "curr_to_lev1")
tar_config_get("script"); tar_config_get("store")
tar_manifest()
tar_outdated()
system.time(tar_make())
system.time(tar_make_future(workers = 10L))

source("_targets_hist_to_lev1.R")
lapply(v_packages, require, character.only = TRUE)
tar_load_everything(strict = FALSE)

tar_visnetwork()
