#!/bin/bash
#SBATCH --job-name=update_amo
#SBATCH --time=00:80:00
#SBATCH --mem=8000
#SBATCH --account=ceh_generic
#SBATCH --partition=standard
#SBATCH --qos=short
#SBATCH -o update_amo_%j.out
#SBATCH -e update_amo_%j.err

umask 002
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/apps/jasmin/jaspy/miniforge_envs/jasr4.3/mf3-23.11.0-0/envs/jasr4.3-mf3-23.11.0-0-v20240815/bin:/apps/jasmin/jaspy/miniforge_envs/jasr4.3/mf3-23.11.0-0/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/users/bkruijt/bin
# #/gws/nopw/j04/ceh_generic/amo_met/data-raw/era5_update.sh
# R CMD BATCH --no-restore --no-save /gws/nopw/j04/ceh_generic/amo_met/Logger_Data_Update.R /gws/nopw/j04/ceh_generic/amo_met/Logger_Data_Update.Rout
# R CMD BATCH --no-restore --no-save /gws/nopw/j04/ceh_generic/amo_met/icos_uploader.R     /gws/nopw/j04/ceh_generic/amo_met/icos_uploader.Rout
R CMD BATCH --no-restore --no-save /gws/nopw/j04/ceh_generic/amo_met/render_icos_plots.R /gws/nopw/j04/ceh_generic/amo_met/render_icos_plots.Rout
cd /gws/nopw/j04/eddystore/cehmet/
R CMD BATCH --no-restore --no-save /gws/nopw/j04/eddystore/cehmet/update_cehmet.R        /gws/nopw/j04/eddystore/cehmet/update_cehmet.Rout
